-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.contractor_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clerk_id character varying,
  company_name character varying NOT NULL,
  cnpj character varying,
  responsible_name character varying NOT NULL,
  responsible_role character varying,
  email character varying NOT NULL,
  phone character varying NOT NULL,
  accepts_whatsapp boolean DEFAULT false,
  website character varying,
  company_address text,
  event_name character varying NOT NULL,
  event_type character varying NOT NULL,
  event_description text,
  start_date date NOT NULL,
  end_date date,
  start_time time without time zone,
  end_time time without time zone,
  expected_attendance integer,
  venue_name character varying,
  venue_address character varying NOT NULL,
  venue_city character varying NOT NULL,
  venue_state character varying NOT NULL,
  venue_zip character varying,
  professionals_needed jsonb,
  needs_equipment boolean DEFAULT false,
  equipment_list ARRAY,
  equipment_other text,
  equipment_notes text,
  budget_range character varying,
  urgency character varying DEFAULT 'normal'::character varying,
  additional_notes text,
  status character varying DEFAULT 'pending'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contractor_requests_pkey PRIMARY KEY (id)
);
CREATE TABLE public.contractors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_name character varying NOT NULL,
  cnpj character varying NOT NULL UNIQUE,
  responsible_name character varying NOT NULL,
  responsible_role character varying,
  email character varying NOT NULL,
  phone character varying NOT NULL,
  company_address text,
  website character varying,
  user_id uuid,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contractors_pkey PRIMARY KEY (id),
  CONSTRAINT contractors_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.document_validations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  professional_id uuid NOT NULL,
  document_type character varying NOT NULL CHECK (document_type::text = ANY (ARRAY['rg_front'::character varying, 'rg_back'::character varying, 'cpf'::character varying, 'proof_of_address'::character varying, 'cnh_photo'::character varying, 'nr10'::character varying, 'nr35'::character varying, 'drt'::character varying, 'cnv'::character varying, 'portfolio'::character varying]::text[])),
  document_url text NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying]::text[])),
  reviewed_by uuid,
  rejection_reason text,
  reviewed_at timestamp with time zone,
  version integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT document_validations_pkey PRIMARY KEY (id),
  CONSTRAINT document_validations_professional_id_fkey FOREIGN KEY (professional_id) REFERENCES public.professionals(id),
  CONSTRAINT document_validations_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id)
);
CREATE TABLE public.email_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  recipient_email character varying NOT NULL,
  recipient_type character varying CHECK (recipient_type::text = ANY (ARRAY['professional'::character varying, 'contractor'::character varying, 'hrx'::character varying, 'admin'::character varying]::text[])),
  subject character varying,
  template_used character varying,
  related_id uuid,
  related_type character varying,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'sent'::character varying, 'failed'::character varying]::text[])),
  error_message text,
  external_id character varying,
  sent_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.equipment_allocations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_id uuid NOT NULL UNIQUE,
  allocations jsonb NOT NULL DEFAULT '[]'::jsonb,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT equipment_allocations_pkey PRIMARY KEY (id),
  CONSTRAINT equipment_allocations_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.contractor_requests(id)
);
CREATE TABLE public.equipment_suppliers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_name text NOT NULL,
  contact_name text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  equipment_types ARRAY NOT NULL DEFAULT '{}'::text[],
  notes text,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  proposed_budget numeric,
  pricing jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT equipment_suppliers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.event_allocations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_id uuid NOT NULL,
  allocations jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT event_allocations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.event_projects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_number character varying NOT NULL UNIQUE,
  client_name character varying NOT NULL,
  client_email character varying,
  client_phone character varying,
  client_company character varying,
  client_cnpj character varying,
  event_name character varying NOT NULL,
  event_type character varying NOT NULL,
  event_description text,
  event_date date,
  start_time time without time zone,
  end_time time without time zone,
  expected_attendance integer,
  venue_name character varying,
  venue_address text NOT NULL,
  venue_city character varying NOT NULL,
  venue_state character varying NOT NULL,
  venue_zip character varying,
  is_urgent boolean DEFAULT false,
  profit_margin numeric NOT NULL DEFAULT 35.00 CHECK (profit_margin = ANY (ARRAY[35.00, 80.00])),
  budget_range character varying,
  status character varying NOT NULL DEFAULT 'new'::character varying CHECK (status::text = ANY (ARRAY['new'::character varying, 'analyzing'::character varying, 'quoting'::character varying, 'quoted'::character varying, 'proposed'::character varying, 'approved'::character varying, 'in_execution'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])),
  total_team_cost numeric DEFAULT 0,
  total_equipment_cost numeric DEFAULT 0,
  total_cost numeric DEFAULT 0,
  total_client_price numeric DEFAULT 0,
  total_profit numeric DEFAULT 0,
  additional_notes text,
  internal_notes text,
  created_by character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  quoted_at timestamp with time zone,
  proposed_at timestamp with time zone,
  approved_at timestamp with time zone,
  completed_at timestamp with time zone,
  migrated_from_contractor_request_id uuid,
  migrated_from_quote_request_id uuid,
  CONSTRAINT event_projects_pkey PRIMARY KEY (id)
);
CREATE TABLE public.event_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT event_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  professional_id uuid NOT NULL,
  request_id uuid,
  type character varying NOT NULL,
  title character varying NOT NULL,
  message text NOT NULL,
  sent_at timestamp with time zone DEFAULT now(),
  read boolean DEFAULT false,
  read_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.professional_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  professional_id uuid NOT NULL,
  action_type character varying NOT NULL,
  action_by uuid,
  field_changed character varying,
  old_value text,
  new_value text,
  description text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT professional_history_pkey PRIMARY KEY (id),
  CONSTRAINT professional_history_professional_id_fkey FOREIGN KEY (professional_id) REFERENCES public.professionals(id),
  CONSTRAINT professional_history_action_by_fkey FOREIGN KEY (action_by) REFERENCES public.users(id)
);
CREATE TABLE public.professionals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  full_name character varying NOT NULL,
  cpf character varying NOT NULL UNIQUE,
  birth_date date NOT NULL,
  email character varying NOT NULL,
  phone character varying NOT NULL,
  cep character varying,
  street character varying,
  number character varying,
  complement character varying,
  neighborhood character varying,
  city character varying,
  state character varying,
  categories jsonb NOT NULL,
  has_experience boolean DEFAULT false,
  experience_description text,
  years_of_experience character varying,
  availability jsonb NOT NULL,
  rg_photo_url character varying,
  cpf_photo_url character varying,
  profile_photo_url character varying,
  proof_of_residence_url character varying,
  certificates jsonb,
  bank_name character varying,
  account_type character varying,
  agency character varying,
  account_number character varying,
  pix_key character varying,
  status character varying DEFAULT 'pending'::character varying,
  accepts_notifications boolean DEFAULT true,
  internal_notes text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  approved_at timestamp without time zone,
  approved_by uuid,
  documents jsonb DEFAULT '{}'::jsonb,
  portfolio jsonb DEFAULT '[]'::jsonb,
  clerk_id character varying,
  rejection_reason text,
  cnh_number character varying,
  cnh_validity date,
  cnv_validity date,
  nr10_validity date,
  nr35_validity date,
  drt_validity date,
  latitude numeric,
  longitude numeric,
  subcategories jsonb DEFAULT '{}'::jsonb,
  certifications jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT professionals_pkey PRIMARY KEY (id),
  CONSTRAINT professionals_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT professionals_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id)
);
CREATE TABLE public.project_emails (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  quotation_id uuid,
  recipient_email character varying NOT NULL,
  recipient_name character varying,
  recipient_type character varying NOT NULL CHECK (recipient_type::text = ANY (ARRAY['client'::character varying, 'supplier'::character varying, 'professional'::character varying, 'hrx_admin'::character varying, 'other'::character varying]::text[])),
  email_type character varying NOT NULL CHECK (email_type::text = ANY (ARRAY['project_created'::character varying, 'quote_request'::character varying, 'quote_urgent_admin'::character varying, 'quote_received'::character varying, 'quote_accepted'::character varying, 'quote_rejected'::character varying, 'proposal_sent'::character varying, 'project_approved'::character varying, 'project_reminder'::character varying, 'project_completed'::character varying, 'other'::character varying]::text[])),
  subject character varying,
  template_used character varying,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'sent'::character varying, 'delivered'::character varying, 'opened'::character varying, 'failed'::character varying]::text[])),
  resend_id character varying,
  error_message text,
  sent_at timestamp with time zone,
  delivered_at timestamp with time zone,
  opened_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT project_emails_pkey PRIMARY KEY (id),
  CONSTRAINT project_emails_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.event_projects(id),
  CONSTRAINT project_emails_quotation_id_fkey FOREIGN KEY (quotation_id) REFERENCES public.supplier_quotations(id)
);
CREATE TABLE public.project_equipment (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  equipment_type character varying NOT NULL,
  category character varying NOT NULL,
  subcategory character varying,
  name character varying NOT NULL,
  description text,
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  duration_days integer NOT NULL DEFAULT 1 CHECK (duration_days > 0),
  specifications jsonb DEFAULT '{}'::jsonb,
  status character varying NOT NULL DEFAULT 'requested'::character varying CHECK (status::text = ANY (ARRAY['requested'::character varying, 'quoting'::character varying, 'quoted'::character varying, 'selected'::character varying, 'confirmed'::character varying, 'delivered'::character varying, 'returned'::character varying, 'cancelled'::character varying]::text[])),
  selected_supplier_id uuid,
  selected_quote_id uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT project_equipment_pkey PRIMARY KEY (id),
  CONSTRAINT project_equipment_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.event_projects(id),
  CONSTRAINT project_equipment_selected_supplier_id_fkey FOREIGN KEY (selected_supplier_id) REFERENCES public.equipment_suppliers(id)
);
CREATE TABLE public.project_team (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  professional_id uuid,
  external_name character varying,
  role character varying NOT NULL,
  category character varying NOT NULL,
  subcategory character varying,
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  duration_days integer NOT NULL DEFAULT 1 CHECK (duration_days > 0),
  daily_rate numeric,
  total_cost numeric,
  status character varying NOT NULL DEFAULT 'planned'::character varying CHECK (status::text = ANY (ARRAY['planned'::character varying, 'invited'::character varying, 'confirmed'::character varying, 'rejected'::character varying, 'allocated'::character varying, 'working'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  invited_at timestamp with time zone,
  confirmed_at timestamp with time zone,
  CONSTRAINT project_team_pkey PRIMARY KEY (id),
  CONSTRAINT project_team_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.event_projects(id),
  CONSTRAINT project_team_professional_id_fkey FOREIGN KEY (professional_id) REFERENCES public.professionals(id)
);
CREATE TABLE public.quote_emails (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quote_request_id uuid NOT NULL,
  supplier_quote_id uuid,
  recipient_email text NOT NULL,
  recipient_name text,
  email_type text NOT NULL CHECK (email_type = ANY (ARRAY['quote_request'::text, 'quote_urgent_admin'::text, 'quote_accepted'::text, 'quote_rejected'::text, 'quote_reminder'::text])),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'sent'::text, 'delivered'::text, 'failed'::text])),
  resend_id text,
  error_message text,
  sent_at timestamp with time zone,
  delivered_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quote_emails_pkey PRIMARY KEY (id),
  CONSTRAINT quote_emails_quote_request_id_fkey FOREIGN KEY (quote_request_id) REFERENCES public.quote_requests(id),
  CONSTRAINT quote_emails_supplier_quote_id_fkey FOREIGN KEY (supplier_quote_id) REFERENCES public.supplier_quotes(id)
);
CREATE TABLE public.quote_request_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quote_request_id uuid NOT NULL,
  item_type text NOT NULL CHECK (item_type = ANY (ARRAY['equipment'::text, 'professional'::text, 'service'::text, 'other'::text])),
  category text NOT NULL,
  subcategory text,
  name text NOT NULL,
  description text,
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  duration_days integer NOT NULL DEFAULT 1 CHECK (duration_days > 0),
  specifications jsonb DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'quoted'::text, 'assigned'::text, 'confirmed'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quote_request_items_pkey PRIMARY KEY (id),
  CONSTRAINT quote_request_items_quote_request_id_fkey FOREIGN KEY (quote_request_id) REFERENCES public.quote_requests(id)
);
CREATE TABLE public.quote_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_name text NOT NULL,
  client_email text,
  client_phone text,
  event_date date,
  event_type text,
  event_location text,
  description text,
  is_urgent boolean DEFAULT false,
  profit_margin numeric NOT NULL CHECK (profit_margin = ANY (ARRAY[35.00, 80.00])),
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'sent'::text, 'analyzing'::text, 'finalized'::text, 'cancelled'::text])),
  total_supplier_cost numeric DEFAULT 0,
  total_client_price numeric DEFAULT 0,
  total_profit numeric DEFAULT 0,
  created_by text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  finalized_at timestamp with time zone,
  CONSTRAINT quote_requests_pkey PRIMARY KEY (id)
);
CREATE TABLE public.requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_number character varying NOT NULL UNIQUE,
  contractor_id uuid,
  event_name character varying NOT NULL,
  event_type character varying NOT NULL,
  event_type_other character varying,
  event_description text,
  venue_name character varying,
  venue_address text NOT NULL,
  venue_city character varying NOT NULL,
  venue_state character varying NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  start_time time without time zone,
  end_time time without time zone,
  expected_attendance integer,
  professionals_needed jsonb NOT NULL,
  needs_equipment boolean DEFAULT false,
  equipment_list jsonb,
  equipment_other text,
  equipment_notes text,
  budget_range character varying,
  urgency character varying DEFAULT 'normal'::character varying CHECK (urgency::text = ANY (ARRAY['normal'::character varying, 'urgent'::character varying, 'very_urgent'::character varying]::text[])),
  additional_notes text,
  status character varying DEFAULT 'new'::character varying CHECK (status::text = ANY (ARRAY['new'::character varying, 'in_progress'::character varying, 'quoted'::character varying, 'hired'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT requests_pkey PRIMARY KEY (id),
  CONSTRAINT requests_contractor_id_fkey FOREIGN KEY (contractor_id) REFERENCES public.contractors(id)
);
CREATE TABLE public.supplier_quotations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  equipment_id uuid NOT NULL,
  supplier_id uuid NOT NULL,
  supplier_price numeric NOT NULL,
  supplier_notes text,
  profit_margin_applied numeric NOT NULL,
  hrx_price numeric NOT NULL,
  profit_amount numeric NOT NULL CHECK (profit_amount >= 0::numeric),
  availability_confirmed boolean DEFAULT false,
  delivery_date date,
  pickup_date date,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'sent'::character varying, 'received'::character varying, 'accepted'::character varying, 'rejected'::character varying, 'expired'::character varying]::text[])),
  deadline timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  sent_at timestamp with time zone,
  received_at timestamp with time zone,
  accepted_at timestamp with time zone,
  rejected_at timestamp with time zone,
  CONSTRAINT supplier_quotations_pkey PRIMARY KEY (id),
  CONSTRAINT supplier_quotations_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.event_projects(id),
  CONSTRAINT supplier_quotations_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES public.project_equipment(id),
  CONSTRAINT supplier_quotations_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.equipment_suppliers(id)
);
CREATE TABLE public.supplier_quotes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quote_request_id uuid NOT NULL,
  quote_request_item_id uuid,
  supplier_id uuid NOT NULL,
  supplier_price numeric NOT NULL,
  hrx_price numeric NOT NULL,
  profit_margin_applied numeric NOT NULL,
  profit_amount numeric NOT NULL CHECK (profit_amount >= 0::numeric),
  description text,
  notes text,
  availability_confirmed boolean DEFAULT false,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'sent'::text, 'received'::text, 'accepted'::text, 'rejected'::text])),
  sent_at timestamp with time zone,
  received_at timestamp with time zone,
  accepted_at timestamp with time zone,
  rejected_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT supplier_quotes_pkey PRIMARY KEY (id),
  CONSTRAINT supplier_quotes_quote_request_id_fkey FOREIGN KEY (quote_request_id) REFERENCES public.quote_requests(id),
  CONSTRAINT supplier_quotes_quote_request_item_id_fkey FOREIGN KEY (quote_request_item_id) REFERENCES public.quote_request_items(id),
  CONSTRAINT supplier_quotes_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.equipment_suppliers(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clerk_id character varying NOT NULL UNIQUE,
  email character varying NOT NULL,
  full_name character varying,
  avatar_url character varying,
  user_type character varying CHECK (user_type::text = ANY (ARRAY['professional'::character varying, 'contractor'::character varying, NULL::character varying]::text[])),
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'deleted'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  role character varying DEFAULT 'user'::character varying CHECK (role::text = ANY (ARRAY['user'::character varying, 'admin'::character varying]::text[])),
  CONSTRAINT users_pkey PRIMARY KEY (id)
);