-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.contractor_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clerk_id character varying,
  company_name character varying NOT NULL,
  cnpj character varying,
  responsible_name character varying NOT NULL,
  responsible_role character varying,
  email character varying NOT NULL,
  phone character varying NOT NULL,
  accepts_whatsapp boolean DEFAULT false,
  website character varying,
  company_address text,
  event_name character varying NOT NULL,
  event_type character varying NOT NULL,
  event_description text,
  start_date date NOT NULL,
  end_date date,
  start_time time without time zone,
  end_time time without time zone,
  expected_attendance integer,
  venue_name character varying,
  venue_address character varying NOT NULL,
  venue_city character varying NOT NULL,
  venue_state character varying NOT NULL,
  venue_zip character varying,
  professionals_needed jsonb,
  needs_equipment boolean DEFAULT false,
  equipment_list ARRAY,
  equipment_other text,
  equipment_notes text,
  budget_range character varying,
  urgency character varying DEFAULT 'normal'::character varying,
  additional_notes text,
  status character varying DEFAULT 'pending'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contractor_requests_pkey PRIMARY KEY (id)
);
CREATE TABLE public.contractors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_name character varying NOT NULL,
  cnpj character varying NOT NULL UNIQUE,
  responsible_name character varying NOT NULL,
  responsible_role character varying,
  email character varying NOT NULL,
  phone character varying NOT NULL,
  company_address text,
  website character varying,
  user_id uuid,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contractors_pkey PRIMARY KEY (id),
  CONSTRAINT contractors_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.document_validations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  professional_id uuid NOT NULL,
  document_type character varying NOT NULL CHECK (document_type::text = ANY (ARRAY['rg_front'::character varying, 'rg_back'::character varying, 'cpf'::character varying, 'proof_of_address'::character varying, 'cnh_photo'::character varying, 'nr10'::character varying, 'nr35'::character varying, 'drt'::character varying, 'cnv'::character varying, 'portfolio'::character varying]::text[])),
  document_url text NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying]::text[])),
  reviewed_by uuid,
  rejection_reason text,
  reviewed_at timestamp with time zone,
  version integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT document_validations_pkey PRIMARY KEY (id),
  CONSTRAINT document_validations_professional_id_fkey FOREIGN KEY (professional_id) REFERENCES public.professionals(id),
  CONSTRAINT document_validations_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id)
);
CREATE TABLE public.email_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  recipient_email character varying NOT NULL,
  recipient_type character varying CHECK (recipient_type::text = ANY (ARRAY['professional'::character varying, 'contractor'::character varying, 'hrx'::character varying, 'admin'::character varying]::text[])),
  subject character varying,
  template_used character varying,
  related_id uuid,
  related_type character varying,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'sent'::character varying, 'failed'::character varying]::text[])),
  error_message text,
  external_id character varying,
  sent_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.equipment_allocations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_id uuid NOT NULL UNIQUE,
  allocations jsonb NOT NULL DEFAULT '[]'::jsonb,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT equipment_allocations_pkey PRIMARY KEY (id),
  CONSTRAINT equipment_allocations_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.contractor_requests(id)
);
CREATE TABLE public.equipment_suppliers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_name text NOT NULL,
  contact_name text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  equipment_types ARRAY NOT NULL DEFAULT '{}'::text[],
  notes text,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  proposed_budget numeric,
  CONSTRAINT equipment_suppliers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.event_allocations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_id uuid NOT NULL,
  allocations jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT event_allocations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.event_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT event_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  professional_id uuid NOT NULL,
  request_id uuid,
  type character varying NOT NULL,
  title character varying NOT NULL,
  message text NOT NULL,
  sent_at timestamp with time zone DEFAULT now(),
  read boolean DEFAULT false,
  read_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.professional_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  professional_id uuid NOT NULL,
  action_type character varying NOT NULL,
  action_by uuid,
  field_changed character varying,
  old_value text,
  new_value text,
  description text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT professional_history_pkey PRIMARY KEY (id),
  CONSTRAINT professional_history_professional_id_fkey FOREIGN KEY (professional_id) REFERENCES public.professionals(id),
  CONSTRAINT professional_history_action_by_fkey FOREIGN KEY (action_by) REFERENCES public.users(id)
);
CREATE TABLE public.professionals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  full_name character varying NOT NULL,
  cpf character varying NOT NULL UNIQUE,
  birth_date date NOT NULL,
  email character varying NOT NULL,
  phone character varying NOT NULL,
  cep character varying,
  street character varying,
  number character varying,
  complement character varying,
  neighborhood character varying,
  city character varying,
  state character varying,
  categories jsonb NOT NULL,
  has_experience boolean DEFAULT false,
  experience_description text,
  years_of_experience character varying,
  availability jsonb NOT NULL,
  rg_photo_url character varying,
  cpf_photo_url character varying,
  profile_photo_url character varying,
  proof_of_residence_url character varying,
  certificates jsonb,
  bank_name character varying,
  account_type character varying,
  agency character varying,
  account_number character varying,
  pix_key character varying,
  status character varying DEFAULT 'pending'::character varying,
  accepts_notifications boolean DEFAULT true,
  internal_notes text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  approved_at timestamp without time zone,
  approved_by uuid,
  documents jsonb DEFAULT '{}'::jsonb,
  portfolio jsonb DEFAULT '[]'::jsonb,
  clerk_id character varying,
  rejection_reason text,
  cnh_number character varying,
  cnh_validity date,
  cnv_validity date,
  nr10_validity date,
  nr35_validity date,
  drt_validity date,
  latitude numeric,
  longitude numeric,
  subcategories jsonb DEFAULT '{}'::jsonb,
  certifications jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT professionals_pkey PRIMARY KEY (id),
  CONSTRAINT professionals_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT professionals_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id)
);
CREATE TABLE public.requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_number character varying NOT NULL UNIQUE,
  contractor_id uuid,
  event_name character varying NOT NULL,
  event_type character varying NOT NULL,
  event_type_other character varying,
  event_description text,
  venue_name character varying,
  venue_address text NOT NULL,
  venue_city character varying NOT NULL,
  venue_state character varying NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  start_time time without time zone,
  end_time time without time zone,
  expected_attendance integer,
  professionals_needed jsonb NOT NULL,
  needs_equipment boolean DEFAULT false,
  equipment_list jsonb,
  equipment_other text,
  equipment_notes text,
  budget_range character varying,
  urgency character varying DEFAULT 'normal'::character varying CHECK (urgency::text = ANY (ARRAY['normal'::character varying, 'urgent'::character varying, 'very_urgent'::character varying]::text[])),
  additional_notes text,
  status character varying DEFAULT 'new'::character varying CHECK (status::text = ANY (ARRAY['new'::character varying, 'in_progress'::character varying, 'quoted'::character varying, 'hired'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT requests_pkey PRIMARY KEY (id),
  CONSTRAINT requests_contractor_id_fkey FOREIGN KEY (contractor_id) REFERENCES public.contractors(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clerk_id character varying NOT NULL UNIQUE,
  email character varying NOT NULL,
  full_name character varying,
  avatar_url character varying,
  user_type character varying CHECK (user_type::text = ANY (ARRAY['professional'::character varying, 'contractor'::character varying, NULL::character varying]::text[])),
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'deleted'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  role character varying DEFAULT 'user'::character varying CHECK (role::text = ANY (ARRAY['user'::character varying, 'admin'::character varying]::text[])),
  CONSTRAINT users_pkey PRIMARY KEY (id)
);