-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  category_type character varying DEFAULT 'professional'::character varying CHECK (category_type::text = ANY (ARRAY['professional'::character varying, 'equipment'::character varying]::text[])),
  icon character varying,
  color character varying,
  order_index integer DEFAULT 0,
  active boolean DEFAULT true,
  CONSTRAINT categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.category_subcategories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category_id uuid NOT NULL,
  name character varying NOT NULL,
  slug character varying NOT NULL,
  description text,
  required_documents jsonb DEFAULT '[]'::jsonb,
  optional_documents jsonb DEFAULT '[]'::jsonb,
  unit character varying,
  suggested_price numeric,
  order_index integer DEFAULT 0,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT category_subcategories_pkey PRIMARY KEY (id),
  CONSTRAINT category_subcategories_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id)
);
CREATE TABLE public.contract_audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contract_id uuid NOT NULL,
  action character varying NOT NULL CHECK (action::text = ANY (ARRAY['generated'::text, 'sent'::text, 'viewed'::text, 'signed'::text, 'downloaded'::text, 'cancelled'::text])),
  performed_by character varying,
  ip_address character varying,
  user_agent text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contract_audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT contract_audit_log_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id)
);
CREATE TABLE public.contractors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_name character varying NOT NULL,
  cnpj character varying NOT NULL UNIQUE,
  responsible_name character varying NOT NULL,
  responsible_role character varying,
  email character varying NOT NULL,
  phone character varying NOT NULL,
  company_address text,
  website character varying,
  user_id uuid,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  clerk_id character varying UNIQUE,
  CONSTRAINT contractors_pkey PRIMARY KEY (id),
  CONSTRAINT contractors_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.contracts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  contract_number character varying NOT NULL UNIQUE,
  contract_type character varying NOT NULL DEFAULT 'service_agreement'::character varying CHECK (contract_type::text = ANY (ARRAY['service_agreement'::character varying::text, 'nda'::character varying::text, 'amendment'::character varying::text])),
  pdf_url text,
  pdf_generated_at timestamp with time zone,
  status character varying NOT NULL DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying::text, 'sent'::character varying::text, 'signed'::character varying::text, 'expired'::character varying::text, 'cancelled'::character varying::text])),
  signature_token character varying UNIQUE,
  token_expires_at timestamp with time zone,
  signature_hash text,
  signed_at timestamp with time zone,
  signed_by_name character varying,
  signed_by_email character varying,
  signed_by_ip character varying,
  contract_data jsonb DEFAULT '{}'::jsonb,
  total_value numeric,
  payment_terms text,
  special_clauses text,
  created_by character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  sent_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  CONSTRAINT contracts_pkey PRIMARY KEY (id),
  CONSTRAINT contracts_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.event_projects(id)
);
CREATE TABLE public.course_badges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  slug text NOT NULL UNIQUE,
  description text NOT NULL,
  icon text,
  color text DEFAULT '#3b82f6'::text,
  image_url text,
  criteria_type text NOT NULL CHECK (criteria_type = ANY (ARRAY['first_course'::text, 'courses_count'::text, 'streak_days'::text, 'average_score'::text, 'category_master'::text, 'quick_learner'::text, 'perfect_score'::text])),
  criteria_value jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  order_index integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT course_badges_pkey PRIMARY KEY (id)
);
CREATE TABLE public.course_enrollments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  course_id uuid NOT NULL,
  professional_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'completed'::text, 'cancelled'::text, 'expired'::text])),
  progress_percentage integer DEFAULT 0 CHECK (progress_percentage >= 0 AND progress_percentage <= 100),
  completed_lessons jsonb DEFAULT '[]'::jsonb,
  quiz_scores jsonb DEFAULT '{}'::jsonb,
  final_score numeric,
  passed boolean DEFAULT false,
  certificate_code text UNIQUE,
  certificate_issued_at timestamp with time zone,
  payment_status text CHECK (payment_status = ANY (ARRAY['pending'::text, 'paid'::text, 'refunded'::text, 'free'::text])),
  payment_amount numeric,
  payment_date timestamp with time zone,
  enrolled_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  expires_at timestamp with time zone,
  last_accessed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT course_enrollments_pkey PRIMARY KEY (id),
  CONSTRAINT course_enrollments_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT course_enrollments_professional_id_fkey FOREIGN KEY (professional_id) REFERENCES public.professionals(id)
);
CREATE TABLE public.course_lessons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  course_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  order_index integer NOT NULL CHECK (order_index >= 0),
  content_type text NOT NULL CHECK (content_type = ANY (ARRAY['video'::text, 'text'::text, 'quiz'::text, 'assignment'::text])),
  video_url text,
  video_duration_seconds integer CHECK (video_duration_seconds >= 0),
  video_provider text CHECK (video_provider = ANY (ARRAY['youtube'::text, 'vimeo'::text, 'supabase'::text, 'other'::text])),
  text_content text,
  quiz_data jsonb,
  attachments jsonb DEFAULT '[]'::jsonb,
  duration_minutes integer DEFAULT 0 CHECK (duration_minutes >= 0),
  is_preview boolean DEFAULT false,
  is_mandatory boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT course_lessons_pkey PRIMARY KEY (id),
  CONSTRAINT course_lessons_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id)
);
CREATE TABLE public.courses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text NOT NULL,
  category text NOT NULL,
  workload_hours integer NOT NULL CHECK (workload_hours > 0),
  difficulty_level text NOT NULL DEFAULT 'beginner'::text CHECK (difficulty_level = ANY (ARRAY['beginner'::text, 'intermediate'::text, 'advanced'::text])),
  is_free boolean NOT NULL DEFAULT true,
  price numeric DEFAULT 0 CHECK (price >= 0::numeric),
  syllabus jsonb DEFAULT '[]'::jsonb,
  learning_objectives jsonb DEFAULT '[]'::jsonb,
  prerequisites text,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'published'::text, 'archived'::text])),
  enrolled_count integer DEFAULT 0 CHECK (enrolled_count >= 0),
  completed_count integer DEFAULT 0 CHECK (completed_count >= 0),
  average_rating numeric DEFAULT 0 CHECK (average_rating >= 0::numeric AND average_rating <= 5::numeric),
  certificate_enabled boolean DEFAULT true,
  minimum_score integer DEFAULT 70 CHECK (minimum_score >= 0 AND minimum_score <= 100),
  cover_image_url text,
  instructor_name text DEFAULT 'Equipe HRX'::text,
  instructor_bio text,
  meta_title text,
  meta_description text,
  published_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT courses_pkey PRIMARY KEY (id)
);
CREATE TABLE public.delivery_location_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  delivery_tracking_id uuid NOT NULL,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  speed_kmh numeric,
  recorded_at timestamp with time zone DEFAULT now(),
  CONSTRAINT delivery_location_history_pkey PRIMARY KEY (id),
  CONSTRAINT delivery_location_history_delivery_tracking_id_fkey FOREIGN KEY (delivery_tracking_id) REFERENCES public.delivery_trackings(id)
);
CREATE TABLE public.delivery_status_updates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  delivery_tracking_id uuid NOT NULL,
  old_status character varying,
  new_status character varying NOT NULL,
  updated_by_user_id uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT delivery_status_updates_pkey PRIMARY KEY (id),
  CONSTRAINT delivery_status_updates_delivery_tracking_id_fkey FOREIGN KEY (delivery_tracking_id) REFERENCES public.delivery_trackings(id),
  CONSTRAINT delivery_status_updates_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.delivery_trackings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_project_id uuid NOT NULL,
  supplier_id uuid NOT NULL,
  supplier_user_id uuid,
  status character varying NOT NULL DEFAULT 'pending'::character varying,
  equipment_items jsonb NOT NULL DEFAULT '[]'::jsonb,
  current_latitude numeric,
  current_longitude numeric,
  last_location_update timestamp with time zone,
  origin_address text,
  origin_latitude numeric,
  origin_longitude numeric,
  destination_address text NOT NULL,
  destination_latitude numeric NOT NULL,
  destination_longitude numeric NOT NULL,
  scheduled_pickup_time timestamp with time zone,
  scheduled_delivery_time timestamp with time zone NOT NULL,
  actual_pickup_time timestamp with time zone,
  actual_delivery_time timestamp with time zone,
  estimated_distance_km numeric,
  estimated_duration_minutes integer,
  notes text,
  delivery_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT delivery_trackings_pkey PRIMARY KEY (id),
  CONSTRAINT delivery_trackings_event_project_id_fkey FOREIGN KEY (event_project_id) REFERENCES public.event_projects(id),
  CONSTRAINT delivery_trackings_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.equipment_suppliers(id),
  CONSTRAINT delivery_trackings_supplier_user_id_fkey FOREIGN KEY (supplier_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.document_validations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  professional_id uuid NOT NULL,
  document_type character varying NOT NULL CHECK (document_type::text = ANY (ARRAY['rg_front'::character varying, 'rg_back'::character varying, 'cpf'::character varying, 'proof_of_address'::character varying, 'cnh_photo'::character varying, 'nr10'::character varying, 'nr35'::character varying, 'drt'::character varying, 'cnv'::character varying, 'portfolio'::character varying]::text[])),
  document_url text NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying]::text[])),
  reviewed_by uuid,
  rejection_reason text,
  reviewed_at timestamp with time zone,
  version integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT document_validations_pkey PRIMARY KEY (id),
  CONSTRAINT document_validations_professional_id_fkey FOREIGN KEY (professional_id) REFERENCES public.professionals(id),
  CONSTRAINT document_validations_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id)
);
CREATE TABLE public.email_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  recipient_email character varying NOT NULL,
  recipient_type character varying CHECK (recipient_type::text = ANY (ARRAY['professional'::character varying, 'contractor'::character varying, 'hrx'::character varying, 'admin'::character varying]::text[])),
  subject character varying,
  template_used character varying,
  related_id uuid,
  related_type character varying,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'sent'::character varying, 'failed'::character varying]::text[])),
  error_message text,
  external_id character varying,
  sent_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.email_template_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  company_name text DEFAULT 'HRX Tecnologia'::text,
  company_logo_url text,
  primary_color text DEFAULT '#DC2626'::text,
  secondary_color text DEFAULT '#EF4444'::text,
  background_color text DEFAULT '#f9fafb'::text,
  text_color text DEFAULT '#1a1a1a'::text,
  contact_email text DEFAULT 'contato@hrxeventos.com.br'::text,
  contact_phone text DEFAULT '(11) 99999-9999'::text,
  contact_whatsapp text DEFAULT '5511999999999'::text,
  contact_website text DEFAULT 'https://hrxeventos.com.br'::text,
  contact_address text,
  social_instagram text,
  social_facebook text,
  social_linkedin text,
  template_texts jsonb DEFAULT '{}'::jsonb,
  footer_text text DEFAULT 'HRX Tecnologia - Conectando profissionais a eventos'::text,
  show_social_links boolean DEFAULT true,
  show_contact_info boolean DEFAULT true,
  is_active boolean DEFAULT false,
  CONSTRAINT email_template_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.equipment_allocations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_id uuid NOT NULL UNIQUE,
  allocations jsonb NOT NULL DEFAULT '[]'::jsonb,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT equipment_allocations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.equipment_suppliers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_name text NOT NULL,
  contact_name text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  equipment_types ARRAY NOT NULL DEFAULT '{}'::text[],
  notes text,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  proposed_budget numeric,
  pricing jsonb DEFAULT '{}'::jsonb,
  latitude numeric,
  longitude numeric,
  address text,
  city text,
  state text,
  zip_code text,
  delivery_radius_km integer DEFAULT 50,
  shipping_fee_per_km numeric DEFAULT 0,
  clerk_id character varying UNIQUE,
  equipment_catalog jsonb DEFAULT '[]'::jsonb,
  legal_name text,
  cnpj character varying,
  CONSTRAINT equipment_suppliers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.event_projects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_number character varying NOT NULL UNIQUE,
  client_name character varying NOT NULL,
  client_email character varying,
  client_phone character varying,
  client_company character varying,
  client_cnpj character varying,
  event_name character varying NOT NULL,
  event_type character varying NOT NULL,
  event_description text,
  event_date date,
  start_time time without time zone,
  end_time time without time zone,
  expected_attendance integer,
  venue_name character varying,
  venue_address text NOT NULL,
  venue_city character varying NOT NULL,
  venue_state character varying NOT NULL,
  venue_zip character varying,
  is_urgent boolean DEFAULT false,
  profit_margin numeric NOT NULL CHECK (profit_margin >= 0::numeric AND profit_margin <= 100::numeric),
  budget_range character varying,
  status character varying NOT NULL DEFAULT 'new'::character varying CHECK (status::text = ANY (ARRAY['new'::character varying, 'analyzing'::character varying, 'quoting'::character varying, 'quoted'::character varying, 'proposed'::character varying, 'approved'::character varying, 'in_execution'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])),
  total_team_cost numeric DEFAULT 0,
  total_equipment_cost numeric DEFAULT 0,
  total_cost numeric DEFAULT 0 CHECK (total_cost >= 0::numeric),
  total_client_price numeric DEFAULT 0 CHECK (total_client_price >= 0::numeric),
  total_profit numeric DEFAULT 0,
  additional_notes text,
  internal_notes text,
  created_by character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  quoted_at timestamp with time zone,
  proposed_at timestamp with time zone,
  approved_at timestamp with time zone,
  completed_at timestamp with time zone,
  migrated_from_contractor_request_id uuid,
  migrated_from_quote_request_id uuid,
  equipment_supplier_id uuid,
  professionals_needed jsonb DEFAULT '[]'::jsonb CHECK (professionals_needed IS NULL OR jsonb_typeof(professionals_needed) = 'array'::text),
  equipment_needed jsonb DEFAULT '[]'::jsonb CHECK (equipment_needed IS NULL OR jsonb_typeof(equipment_needed) = 'array'::text),
  latitude numeric,
  longitude numeric,
  client_budget numeric,
  CONSTRAINT event_projects_pkey PRIMARY KEY (id),
  CONSTRAINT event_projects_equipment_supplier_id_fkey FOREIGN KEY (equipment_supplier_id) REFERENCES public.equipment_suppliers(id)
);
CREATE TABLE public.event_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT event_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notification_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  email_enabled boolean DEFAULT true,
  push_enabled boolean DEFAULT true,
  sms_enabled boolean DEFAULT false,
  notify_project_updates boolean DEFAULT true,
  notify_invitations boolean DEFAULT true,
  notify_quotations boolean DEFAULT true,
  notify_documents boolean DEFAULT true,
  notify_payments boolean DEFAULT true,
  notify_reminders boolean DEFAULT true,
  digest_frequency text DEFAULT 'instant'::text CHECK (digest_frequency = ANY (ARRAY['instant'::text, 'hourly'::text, 'daily'::text, 'weekly'::text, 'never'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT notification_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  user_type text NOT NULL CHECK (user_type = ANY (ARRAY['admin'::text, 'professional'::text, 'contractor'::text, 'supplier'::text, 'client'::text])),
  notification_type text NOT NULL CHECK (notification_type = ANY (ARRAY['project_created'::text, 'project_status_changed'::text, 'invitation_received'::text, 'invitation_accepted'::text, 'invitation_rejected'::text, 'quotation_received'::text, 'quotation_accepted'::text, 'document_approved'::text, 'document_rejected'::text, 'document_expiring'::text, 'team_incomplete'::text, 'proposal_sent'::text, 'payment_received'::text, 'event_reminder'::text, 'system_alert'::text])),
  title text NOT NULL,
  message text NOT NULL,
  action_url text,
  project_id uuid,
  professional_id uuid,
  supplier_id uuid,
  is_read boolean DEFAULT false,
  read_at timestamp with time zone,
  priority text DEFAULT 'normal'::text CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'urgent'::text])),
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT notifications_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.event_projects(id),
  CONSTRAINT notifications_professional_id_fkey FOREIGN KEY (professional_id) REFERENCES public.professionals(id),
  CONSTRAINT notifications_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.equipment_suppliers(id)
);
CREATE TABLE public.professional_badges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  professional_id uuid NOT NULL,
  badge_id uuid NOT NULL,
  earned_at timestamp with time zone NOT NULL DEFAULT now(),
  related_course_id uuid,
  achievement_data jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT professional_badges_pkey PRIMARY KEY (id),
  CONSTRAINT professional_badges_professional_id_fkey FOREIGN KEY (professional_id) REFERENCES public.professionals(id),
  CONSTRAINT professional_badges_badge_id_fkey FOREIGN KEY (badge_id) REFERENCES public.course_badges(id),
  CONSTRAINT professional_badges_related_course_id_fkey FOREIGN KEY (related_course_id) REFERENCES public.courses(id)
);
CREATE TABLE public.professional_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  professional_id uuid NOT NULL,
  action_type character varying NOT NULL,
  action_by uuid,
  field_changed character varying,
  old_value text,
  new_value text,
  description text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT professional_history_pkey PRIMARY KEY (id),
  CONSTRAINT professional_history_professional_id_fkey FOREIGN KEY (professional_id) REFERENCES public.professionals(id),
  CONSTRAINT professional_history_action_by_fkey FOREIGN KEY (action_by) REFERENCES public.users(id)
);
CREATE TABLE public.professional_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  team_member_id uuid NOT NULL,
  professional_id uuid NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment text,
  punctuality_rating integer CHECK (punctuality_rating >= 1 AND punctuality_rating <= 5),
  professionalism_rating integer CHECK (professionalism_rating >= 1 AND professionalism_rating <= 5),
  quality_rating integer CHECK (quality_rating >= 1 AND quality_rating <= 5),
  communication_rating integer CHECK (communication_rating >= 1 AND communication_rating <= 5),
  would_hire_again boolean DEFAULT true,
  reviewed_by uuid,
  is_visible boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT professional_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT professional_reviews_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.event_projects(id),
  CONSTRAINT professional_reviews_team_member_id_fkey FOREIGN KEY (team_member_id) REFERENCES public.project_team(id),
  CONSTRAINT professional_reviews_professional_id_fkey FOREIGN KEY (professional_id) REFERENCES public.professionals(id),
  CONSTRAINT professional_reviews_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id)
);
CREATE TABLE public.professionals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  full_name character varying NOT NULL,
  cpf character varying NOT NULL UNIQUE,
  birth_date date NOT NULL,
  email character varying NOT NULL,
  phone character varying NOT NULL,
  cep character varying,
  street character varying,
  number character varying,
  complement character varying,
  neighborhood character varying,
  city character varying,
  state character varying,
  categories jsonb NOT NULL,
  has_experience boolean DEFAULT false,
  experience_description text,
  years_of_experience character varying,
  availability jsonb NOT NULL,
  rg_photo_url character varying,
  cpf_photo_url character varying,
  profile_photo_url character varying,
  proof_of_residence_url character varying,
  certificates jsonb,
  bank_name character varying,
  account_type character varying,
  agency character varying,
  account_number character varying,
  pix_key character varying,
  status character varying DEFAULT 'pending'::character varying,
  accepts_notifications boolean DEFAULT true,
  internal_notes text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  approved_at timestamp without time zone,
  approved_by uuid,
  documents jsonb DEFAULT '{}'::jsonb,
  portfolio jsonb DEFAULT '[]'::jsonb,
  clerk_id character varying UNIQUE,
  rejection_reason text,
  cnh_number character varying,
  cnh_validity date,
  cnv_validity date,
  nr10_validity date,
  nr35_validity date,
  drt_validity date,
  latitude numeric,
  longitude numeric,
  subcategories jsonb DEFAULT '{}'::jsonb,
  certifications jsonb DEFAULT '{}'::jsonb,
  service_radius_km integer DEFAULT 50 CHECK (service_radius_km >= 5 AND service_radius_km <= 500),
  CONSTRAINT professionals_pkey PRIMARY KEY (id),
  CONSTRAINT professionals_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT professionals_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id)
);
CREATE TABLE public.project_emails (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  quotation_id uuid,
  recipient_email character varying NOT NULL,
  recipient_name character varying,
  recipient_type character varying NOT NULL CHECK (recipient_type::text = ANY (ARRAY['client'::character varying, 'supplier'::character varying, 'professional'::character varying, 'hrx_admin'::character varying, 'other'::character varying]::text[])),
  email_type character varying NOT NULL CHECK (email_type::text = ANY (ARRAY['project_created'::character varying, 'quote_request'::character varying, 'quote_urgent_admin'::character varying, 'quote_received'::character varying, 'quote_accepted'::character varying, 'quote_rejected'::character varying, 'proposal_sent'::character varying, 'project_approved'::character varying, 'project_reminder'::character varying, 'project_completed'::character varying, 'other'::character varying]::text[])),
  subject character varying,
  template_used character varying,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'sent'::character varying, 'delivered'::character varying, 'opened'::character varying, 'failed'::character varying]::text[])),
  resend_id character varying,
  error_message text,
  sent_at timestamp with time zone,
  delivered_at timestamp with time zone,
  opened_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT project_emails_pkey PRIMARY KEY (id),
  CONSTRAINT project_emails_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.event_projects(id)
);
CREATE TABLE public.project_equipment (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  equipment_type character varying NOT NULL,
  category character varying NOT NULL,
  subcategory character varying,
  name character varying NOT NULL,
  description text,
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  duration_days integer NOT NULL DEFAULT 1 CHECK (duration_days > 0),
  specifications jsonb DEFAULT '{}'::jsonb,
  status character varying NOT NULL DEFAULT 'requested'::character varying CHECK (status::text = ANY (ARRAY['requested'::character varying, 'quoting'::character varying, 'quoted'::character varying, 'selected'::character varying, 'confirmed'::character varying, 'delivered'::character varying, 'returned'::character varying, 'cancelled'::character varying]::text[])),
  selected_supplier_id uuid,
  selected_quote_id uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  daily_rate numeric DEFAULT 0 CHECK (daily_rate IS NULL OR daily_rate >= 0::numeric),
  total_cost numeric DEFAULT 0,
  CONSTRAINT project_equipment_pkey PRIMARY KEY (id),
  CONSTRAINT project_equipment_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.event_projects(id),
  CONSTRAINT project_equipment_selected_supplier_id_fkey FOREIGN KEY (selected_supplier_id) REFERENCES public.equipment_suppliers(id)
);
CREATE TABLE public.project_team (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  professional_id uuid,
  external_name character varying,
  role character varying NOT NULL,
  category character varying NOT NULL,
  subcategory character varying,
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  duration_days integer NOT NULL DEFAULT 1 CHECK (duration_days > 0),
  daily_rate numeric CHECK (daily_rate IS NULL OR daily_rate >= 0::numeric),
  total_cost numeric,
  status character varying NOT NULL DEFAULT 'planned'::character varying CHECK (status::text = ANY (ARRAY['planned'::character varying, 'invited'::character varying, 'confirmed'::character varying, 'rejected'::character varying, 'allocated'::character varying, 'working'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  invited_at timestamp with time zone,
  confirmed_at timestamp with time zone,
  invitation_token character varying UNIQUE,
  token_expires_at timestamp with time zone,
  CONSTRAINT project_team_pkey PRIMARY KEY (id),
  CONSTRAINT project_team_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.event_projects(id),
  CONSTRAINT project_team_professional_id_fkey FOREIGN KEY (professional_id) REFERENCES public.professionals(id)
);
CREATE TABLE public.rate_limits (
  identifier character varying NOT NULL,
  count integer NOT NULL DEFAULT 1,
  window_start timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '00:01:00'::interval),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT rate_limits_pkey PRIMARY KEY (identifier)
);
CREATE TABLE public.service_order_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  service_order_id uuid NOT NULL,
  action_type character varying NOT NULL CHECK (action_type::text = ANY (ARRAY['created'::character varying, 'status_changed'::character varying, 'task_completed'::character varying, 'email_sent'::character varying, 'updated'::character varying, 'cancelled'::character varying, 'comment_added'::character varying]::text[])),
  description text NOT NULL,
  old_value text,
  new_value text,
  performed_by character varying,
  performed_by_type character varying CHECK (performed_by_type::text = ANY (ARRAY['admin'::character varying, 'professional'::character varying, 'supplier'::character varying, 'system'::character varying, 'ai'::character varying]::text[])),
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT service_order_logs_pkey PRIMARY KEY (id),
  CONSTRAINT service_order_logs_service_order_id_fkey FOREIGN KEY (service_order_id) REFERENCES public.service_orders(id)
);
CREATE TABLE public.service_order_tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  service_order_id uuid NOT NULL,
  title character varying NOT NULL,
  description text,
  category character varying NOT NULL CHECK (category::text = ANY (ARRAY['setup'::character varying, 'operation'::character varying, 'monitoring'::character varying, 'teardown'::character varying, 'logistics'::character varying, 'other'::character varying]::text[])),
  assigned_to_type character varying CHECK (assigned_to_type::text = ANY (ARRAY['professional'::character varying, 'supplier'::character varying, 'hrx_team'::character varying, 'all'::character varying]::text[])),
  assigned_to_id uuid,
  assigned_to_name character varying,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'skipped'::character varying]::text[])),
  estimated_duration_minutes integer,
  scheduled_time time without time zone,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  priority character varying DEFAULT 'normal'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'normal'::character varying, 'high'::character varying, 'critical'::character varying]::text[])),
  sequence_order integer NOT NULL DEFAULT 0,
  depends_on_task_ids ARRAY DEFAULT ARRAY[]::uuid[],
  notes text,
  completion_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT service_order_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT service_order_tasks_service_order_id_fkey FOREIGN KEY (service_order_id) REFERENCES public.service_orders(id)
);
CREATE TABLE public.service_order_timeline (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  service_order_id uuid NOT NULL,
  title character varying NOT NULL,
  description text,
  event_type character varying NOT NULL CHECK (event_type::text = ANY (ARRAY['arrival'::character varying, 'setup_start'::character varying, 'setup_complete'::character varying, 'event_start'::character varying, 'event_end'::character varying, 'teardown_start'::character varying, 'teardown_complete'::character varying, 'departure'::character varying, 'delivery'::character varying, 'pickup'::character varying, 'checkpoint'::character varying, 'other'::character varying]::text[])),
  scheduled_time time without time zone NOT NULL,
  estimated_duration_minutes integer,
  involved_roles ARRAY DEFAULT ARRAY[]::character varying[],
  status character varying DEFAULT 'scheduled'::character varying CHECK (status::text = ANY (ARRAY['scheduled'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'delayed'::character varying, 'cancelled'::character varying]::text[])),
  actual_time timestamp with time zone,
  delay_minutes integer,
  sequence_order integer NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT service_order_timeline_pkey PRIMARY KEY (id),
  CONSTRAINT service_order_timeline_service_order_id_fkey FOREIGN KEY (service_order_id) REFERENCES public.service_orders(id)
);
CREATE TABLE public.service_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  contract_id uuid NOT NULL,
  os_number character varying NOT NULL UNIQUE,
  title character varying NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])),
  event_date date NOT NULL,
  event_start_time time without time zone,
  event_end_time time without time zone,
  ai_briefing text NOT NULL,
  ai_recommendations text,
  ai_alerts text,
  venue_name character varying,
  venue_address text NOT NULL,
  venue_city character varying NOT NULL,
  venue_state character varying NOT NULL,
  venue_latitude numeric,
  venue_longitude numeric,
  estimated_setup_duration_minutes integer,
  estimated_teardown_duration_minutes integer,
  recommended_arrival_time time without time zone,
  distance_from_base_km numeric,
  estimated_travel_time_minutes integer,
  traffic_analysis jsonb DEFAULT '{}'::jsonb,
  route_details jsonb DEFAULT '{}'::jsonb,
  client_name character varying NOT NULL,
  client_email character varying,
  client_phone character varying,
  venue_contact_name character varying,
  venue_contact_phone character varying,
  team_assignments jsonb DEFAULT '[]'::jsonb,
  equipment_list jsonb DEFAULT '[]'::jsonb,
  supplier_assignments jsonb DEFAULT '[]'::jsonb,
  checklist jsonb DEFAULT '[]'::jsonb,
  timeline jsonb DEFAULT '[]'::jsonb,
  special_instructions text,
  internal_notes text,
  generated_by character varying DEFAULT 'ai_system'::character varying,
  generated_at timestamp with time zone DEFAULT now(),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT service_orders_pkey PRIMARY KEY (id),
  CONSTRAINT service_orders_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.event_projects(id),
  CONSTRAINT service_orders_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id)
);
CREATE TABLE public.supplier_quotations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  supplier_id uuid NOT NULL,
  token character varying NOT NULL UNIQUE,
  requested_items jsonb NOT NULL DEFAULT '[]'::jsonb,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'submitted'::character varying, 'accepted'::character varying, 'rejected'::character varying, 'expired'::character varying]::text[])),
  total_price numeric,
  daily_rate numeric,
  delivery_fee numeric DEFAULT 0,
  setup_fee numeric DEFAULT 0,
  payment_terms text,
  delivery_details text,
  notes text,
  valid_until timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  submitted_at timestamp with time zone,
  responded_at timestamp with time zone,
  CONSTRAINT supplier_quotations_pkey PRIMARY KEY (id),
  CONSTRAINT supplier_quotations_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.event_projects(id),
  CONSTRAINT supplier_quotations_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.equipment_suppliers(id)
);
CREATE TABLE public.supplier_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  quotation_id uuid NOT NULL,
  supplier_id uuid NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment text,
  delivery_rating integer CHECK (delivery_rating >= 1 AND delivery_rating <= 5),
  equipment_quality_rating integer CHECK (equipment_quality_rating >= 1 AND equipment_quality_rating <= 5),
  service_rating integer CHECK (service_rating >= 1 AND service_rating <= 5),
  price_value_rating integer CHECK (price_value_rating >= 1 AND price_value_rating <= 5),
  would_hire_again boolean DEFAULT true,
  reviewed_by uuid,
  is_visible boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT supplier_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT supplier_reviews_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.event_projects(id),
  CONSTRAINT supplier_reviews_quotation_id_fkey FOREIGN KEY (quotation_id) REFERENCES public.supplier_quotations(id),
  CONSTRAINT supplier_reviews_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.equipment_suppliers(id),
  CONSTRAINT supplier_reviews_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clerk_id character varying NOT NULL UNIQUE,
  email character varying NOT NULL,
  full_name character varying,
  avatar_url character varying,
  user_type character varying CHECK (user_type::text = ANY (ARRAY['professional'::character varying, 'contractor'::character varying, 'supplier'::character varying, 'admin'::character varying]::text[])),
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'deleted'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_admin boolean DEFAULT false,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);